# Generated by Django 5.2.8 on 2025-11-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_followers_followrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='students.student'),
        ),
    ]
