# Generated by Django 5.2.8 on 2025-11-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='students.student'),
        ),
    ]
