# Generated by Django 5.2.8 on 2025-11-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_followers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
    ]
