# Generated by Django 5.2.8 on 2025-11-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_followrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
