# Generated by Django 5.2.8 on 2025-11-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_interest_skill_experience_student_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='student', to='students.interest'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='student', to='students.skill'),
        ),
    ]
