# Generated by Django 5.2.8 on 2025-11-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_interests_alter_student_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
