# Generated by Django 5.2.8 on 2025-12-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.TextField(default='College Name', max_length=300),
        ),
    ]
