# Generated by Django 5.2.8 on 2025-12-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.TextField(max_length=300),
        ),
    ]
