# Generated by Django 5.2.8 on 2025-12-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='years',
            field=models.FloatField(default=0),
        ),
    ]
